# Generated by Django 4.0.4 on 2022-04-16 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Firmware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Model_Number',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_number', models.CharField(max_length=255)),
                ('firmware', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='robots.firmware')),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=255)),
                ('slots', models.IntegerField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Robot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('module_capacity', models.IntegerField()),
                ('status', models.CharField(choices=[('N', 'Online'), ('F', 'Offline'), ('E', 'Error')], max_length=1)),
                ('built', models.DateTimeField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('firmware', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='robots.firmware')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='robots.model_number')),
                ('modules', models.ManyToManyField(to='robots.module')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='robots.owner')),
            ],
        ),
        migrations.AddField(
            model_name='owner',
            name='owner_robot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='robots.robot'),
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='robots.owner')),
            ],
        ),
    ]
