version: '3'
services:
  website:
    build: ./backend
    volumes:
      - ./backend:/app
      - /dev/null:/backend/robots/migrations/*.py
    ports:
      - 8000:8000
    environment:
      - DATABASE_NAME=robots
      - DATABASE_USER=root
      - DATABASE_PASSWORD=Temporary_Password
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_PASSWORD=Temporary_Password
      - DJANGO_SUPERUSER_EMAIL=jasonmckeeotatrash@gmail.com
      - DATABASE_DATA=mock-data.sql
    depends_on:
      - "db"
    command: ./docker-entrypoint.sh

  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: Temporary_Password
      user: "1000:50"
      
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 5001:80
    environment:
      - PMA_ARBITRARY=1
    depends_on:
      - "db"