version: '3'
services:
  website:
    build: ./backend
    volumes:
      - ./backend:/app
    ports:
      - 8000:8000
    environment:
      - DATABASE_NAME=robots
      - DATABASE_USER=root
      - DATABASE_PASSWORD=Temporary_Password
    depends_on:
      - "db"
    command: sh -c "./wait-for.sh db:3306 && mysql -h db -u root -pTemporary_Password -e \"CREATE DATABASE IF NOT EXISTS robots\" && python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    # command: sh -c "./wait-for db:3306 && python manage.py runserver 0.0.0.0:8000"

  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: Temporary_Password
      user: "1000:50"
      
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 5001:80
    environment:
      - PMA_ARBITRARY=1