version: '3'
services:
  website:
    build: ./backend
    volumes:
      - ./backend:/app
      - /dev/null:/backend/robots/migrations/*.py
    ports:
      - 8000:8000
    environment:
      - DATABASE_NAME=robots
      - DATABASE_USER=root
      - DATABASE_PASSWORD=Temporary_Password
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_PASSWORD=Temporary_Password
      - DJANGO_SUPERUSER_EMAIL=jasonmckeeotatrash@gmail.com
    depends_on:
      - "db"
      # sed -e "s/^insert into/insert ignore into/gI" < mock-data.sql
      #Find out a way to make it case insensitive
    command: sh -c "./wait-for.sh db:3306 && mysql -h db -u root -pTemporary_Password -e \"CREATE DATABASE IF NOT EXISTS robots\" && python manage.py makemigrations && python manage.py migrate && sed -e 's/insert into/insert ignore into/gI' < mock-data.sql | mysql -h db -u root -pTemporary_Password robots && python manage.py createsuperuser --noinput && python manage.py runserver 0.0.0.0:8000"
    # command: sh -c "./wait-for.sh db:3306 && mysql -h db -u root -pTemporary_Password -e \"CREATE DATABASE IF NOT EXISTS robots\" && python manage.py makemigrations && python manage.py migrate && mysql -h db -u root -pTemporary_Password robots < mock-data.sql && python manage.py createsuperuser --noinput && python manage.py runserver 0.0.0.0:8000"
    # command: sh -c "./wait-for db:3306 && python manage.py runserver 0.0.0.0:8000"

  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: Temporary_Password
      user: "1000:50"
      
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 5001:80
    environment:
      - PMA_ARBITRARY=1