FROM python:alpine3.15
ENV PYTHONBUFFERD=1
ENV PYTHONWRITEBYTECODE=1
WORKDIR /app
RUN apk update
#The following is needed for mysqlclient
RUN apk add mariadb-dev
RUN apk add build-base
RUN apk add mariadb-client

#The following is needed for djoser
RUN apk add libffi-dev

#Install pip and requirements
RUN apk add --update py3-pip
RUN pip install pipenv
COPY . .
RUN pipenv install --system
RUN python manage.py makemigrations
# RUN python manage.py migrate
EXPOSE 8000
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]